apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  cluster:
    clusterName: "local"  # Name of your local Kubernetes cluster
    environmentGitOwner: "your-git-username"  # Owner of the Git repository for environments
    gitKind: "github"  # Git provider (e.g., github, gitlab, bitbucket)
    gitServer: "https://github.com"  # Git server URL
    provider: "kubernetes"  # Cloud provider (e.g., kubernetes, eks, gke)
  environments:
    - key: dev
      kind: Development
  ingress:
    domain: "127.0.0.1.nip.io"  # Domain for ingress (customize as needed)
    externalDNS: false  # Whether to use external DNS for ingress
    namespaceSubDomain: "-jx."  # Subdomain for namespaces
    tls:
      email: ""  # Email for TLS certificate
      enabled: false  # Enable TLS
      production: false  # Use self-signed certificates for local development
  repository: nexus  # Specify your repository type (e.g., nexus, artifactory)
  secretStorage: local  # Secret storage method (local, vault, etc.)
  storage:
    backup:
      enabled: false  # Enable backup storage
      url: ""  # URL for backup storage
    logs:
      enabled: true  # Enable log storage
      url: "http://bucketrepo.jx.svc.cluster.local/bucketrepo/logs"  # Local path for log storage
    reports:
      enabled: true  # Enable report storage
      url: "http://bucketrepo.jx.svc.cluster.local/bucketrepo/reports"  # Local path for report storage
    repository:
      enabled: true  # Enable repository storage
      url: "http://bucketrepo.jx.svc.cluster.local/bucketrepo/repository"  # Local path for repository storage
  vault:
    disableURLDiscovery: true  # Disable automatic URL discovery for Vault
  versionStream:
    ref: "master"  # Git reference for version stream
    url: "https://github.com/jenkins-x/jenkins-x-versions.git"  # URL for the Jenkins X versions repository
  webhook: lighthouse  # Webhook type for version stream updates
