apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  cluster:
    clusterName: "docker-desktop"  # Name of your local Kubernetes cluster
    environmentGitOwner: "arun4d"  # Owner of the Git repository for environments
    gitKind: "github"  # Git provider (e.g., github, gitlab, bitbucket)
    gitServer: "https://github.com"  # Git server URL
    provider: "kubernetes"  # Cloud provider (e.g., kubernetes, eks, gke)
  environments:
    - key: dev
  ingress:
    domain: "127.0.0.1.nip.io"  # Domain for ingress (customize as needed)
    externalDNS: false  # Whether to use external DNS for ingress
    namespaceSubDomain: "-jx."  # Subdomain for namespaces
    tls:
      email: ""  # Email for TLS certificate
      enabled: false  # Enable TLS
      production: false  # Use self-signed certificates for local development
  repository: nexus  # Specify your repository type (e.g., nexus, artifactory)
  secretStorage: local  # Secret storage method (local, vault, etc.)
  vault:
    disableURLDiscovery: true  # Disable automatic URL discovery for Vault
  webhook: lighthouse  # Webhook type for version stream updates
